version: '3'

services:
  server:
    build:
      context: ./examples/16-angular-d3-real-time-socket-io/server
      dockerfile: ./Dockerfile
    container_name: 'angular-d3-real-time-socket-io-server'
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ./examples/16-angular-d3-real-time-socket-io/server/src:/app/src
      # We are specifying an anonymous volume here so that our local node_modules directory does not override node_modules installed in our container
      - '/app/node_modules'
    command: sh -c './node_modules/.bin/nodemon ./src/index.js -e js,json'
    ports:
      - "3000:3000"
      - "9229:9229"
